name: deploy

on:
  push:
    branches:
    - main
    paths-ignore:
    - '*.md'

jobs:
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::894701643407:role/GitHubPersonalPageRoleForDeployment
        aws-region: ${{ vars.AWS_REGION }}

    - name: Get CloudFront Distribution Id
      run: echo "AWS_CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudfront list-distributions --output text --query DistributionList.Items[0].Id)" >> $GITHUB_ENV

    - name: Deploy Static Site
      run: aws s3 sync ./public/ s3://preston.vantonder.dev --delete

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
