name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Get CloudFront Distribution Id
      run: echo "AWS_CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudfront list-distributions --output text --query DistributionList.Items[0].Id)" >> $GITHUB_ENV

    - name: Deploy Static Site
      run: aws s3 sync ./public/ s3://preston.vantonder.dev --delete

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
